/** @type {import('tailwindcss').Config} */
import typography from "@tailwindcss/typography";

export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: {
          50: "#eff6ff",
          100: "#dbeafe",
          200: "#bfdbfe",
          300: "#93c5fd",
          400: "#60a5fa",
          500: "#3b82f6",
          600: "#2563eb",
          700: "#1d4ed8",
          800: "#1e40af",
          900: "#1e3a8a",
          950: "#172554",
        },
        navy: {
          50: "#f0f4ff",
          100: "#e0e7ff",
          200: "#c7d2fe",
          300: "#a5b4fc",
          400: "#818cf8",
          500: "#6366f1",
          600: "#4f46e5",
          700: "#4338ca",
          800: "#3730a3",
          900: "#312e81",
          950: "#0b1846",
        },
        neutral: {
          50: "#fafafa",
          100: "#f5f5f5",
          200: "#e5e5e5",
          300: "#d4d4d4",
          400: "#a3a3a3",
          500: "#737373",
          600: "#525252",
          700: "#404040",
          800: "#262626",
          900: "#171717",
          950: "#0a0a0a",
        },
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        display: ["Poppins", "system-ui", "sans-serif"],
        serif: ["Playfair Display", "Georgia", "serif"],
      },
      fontSize: {
        xs: ["0.75rem", { lineHeight: "1rem" }],
        sm: ["0.875rem", { lineHeight: "1.25rem" }],
        base: ["1rem", { lineHeight: "1.5rem" }],
        lg: ["1.125rem", { lineHeight: "1.75rem" }],
        xl: ["1.25rem", { lineHeight: "1.75rem" }],
        "2xl": ["1.5rem", { lineHeight: "2rem" }],
        "3xl": ["1.875rem", { lineHeight: "2.25rem" }],
        "4xl": ["2.25rem", { lineHeight: "2.5rem" }],
        "5xl": ["3rem", { lineHeight: "1" }],
        "6xl": ["3.75rem", { lineHeight: "1" }],
        "7xl": ["4.5rem", { lineHeight: "1" }],
        "8xl": ["6rem", { lineHeight: "1" }],
        "9xl": ["8rem", { lineHeight: "1" }],
      },
      spacing: {
        18: "4.5rem",
        88: "22rem",
        128: "32rem",
      },
      borderRadius: {
        "4xl": "2rem",
      },
      boxShadow: {
        soft: "0 2px 15px -3px rgba(0, 0, 0, 0.07), 0 10px 20px -2px rgba(0, 0, 0, 0.04)",
        medium:
          "0 4px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)",
        large:
          "0 10px 40px -10px rgba(0, 0, 0, 0.1), 0 2px 10px -2px rgba(0, 0, 0, 0.05)",
        "2xl": "0 25px 50px -12px rgba(0, 0, 0, 0.25)",
        "3xl": "0 35px 60px -12px rgba(0, 0, 0, 0.3)",
      },
      animation: {
        "fade-in": "fadeIn 0.5s ease-in-out",
        "slide-up": "slideUp 0.5s ease-out",
        "slide-down": "slideDown 0.5s ease-out",
        "scale-in": "scaleIn 0.3s ease-out",
        "bounce-subtle": "bounceSubtle 2s infinite",
        "marquee-scroll": "marqueeScroll 40s linear infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { transform: "translateY(20px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        slideDown: {
          "0%": { transform: "translateY(-20px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        scaleIn: {
          "0%": { transform: "scale(0.95)", opacity: "0" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
        bounceSubtle: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-5px)" },
        },
        marqueeScroll: {
          from: { transform: "translateX(0)" },
          to: { transform: "translateX(-50%)" },
        },
      },
      typography: ({ theme }) => ({
        blog: {
          css: {
            maxWidth: "68ch",
            color: theme("colors.neutral.700"),
            fontSize: "1.0625rem",
            lineHeight: "1.85",
            "--tw-prose-body": theme("colors.neutral.700"),
            "--tw-prose-headings": theme("colors.neutral.900"),
            "--tw-prose-links": theme("colors.primary.600"),
            "--tw-prose-bold": theme("colors.neutral.900"),
            "--tw-prose-bullets": theme("colors.primary.400"),
            "--tw-prose-counters": theme("colors.primary.500"),
            p: {
              marginTop: "1.35em",
              marginBottom: "1.35em",
            },
            "p:first-child": {
              marginTop: 0,
            },
            h2: {
              fontFamily: theme("fontFamily.display").join(", "),
              fontWeight: "700",
              fontSize: "1.875rem",
              lineHeight: "1.3",
              marginTop: "2.75em",
              marginBottom: "1em",
              letterSpacing: "-0.02em",
              color: theme("colors.neutral.900"),
            },
            "h2:first-child": {
              marginTop: 0,
            },
            h3: {
              fontFamily: theme("fontFamily.display").join(", "),
              fontWeight: "600",
              fontSize: "1.3125rem",
              lineHeight: "1.4",
              marginTop: "2em",
              marginBottom: "0.75em",
              color: theme("colors.neutral.800"),
            },
            "h2 + h3": {
              marginTop: "1.25em",
            },
            h4: {
              fontFamily: theme("fontFamily.display").join(", "),
              fontWeight: "600",
              fontSize: "1.125rem",
              lineHeight: "1.45",
              marginTop: "1.5em",
              marginBottom: "0.5em",
              color: theme("colors.neutral.800"),
            },
            h5: {
              fontSize: "1rem",
              fontWeight: "600",
              marginTop: "1.25em",
              marginBottom: "0.375em",
            },
            h6: {
              fontSize: "0.875rem",
              fontWeight: "600",
              textTransform: "uppercase",
              letterSpacing: "0.05em",
              color: theme("colors.neutral.500"),
            },
            ul: {
              marginTop: "1.25em",
              marginBottom: "1.25em",
              paddingLeft: "1.5em",
            },
            ol: {
              marginTop: "1.25em",
              marginBottom: "1.25em",
              paddingLeft: "1.5em",
            },
            li: {
              marginTop: "0.45em",
              marginBottom: "0.45em",
              paddingLeft: "0.35em",
            },
            "li > p": {
              marginTop: "0.4em",
              marginBottom: "0.4em",
            },
            strong: {
              fontWeight: "600",
              color: theme("colors.neutral.900"),
            },
            a: {
              color: theme("colors.primary.600"),
              fontWeight: "500",
              textDecoration: "underline",
              textDecorationColor: theme("colors.primary.200"),
              textUnderlineOffset: "3px",
              "&:hover": {
                color: theme("colors.primary.700"),
                textDecorationColor: theme("colors.primary.400"),
              },
            },
            blockquote: {
              borderLeftColor: theme("colors.primary.300"),
              backgroundColor: theme("colors.primary.50"),
              borderRadius: "0 0.75rem 0.75rem 0",
              padding: "1rem 1.25rem",
              fontStyle: "normal",
              color: theme("colors.neutral.700"),
            },
            table: {
              fontSize: "0.9375rem",
              lineHeight: "1.6",
              width: "100%",
              marginTop: "1.75em",
              marginBottom: "1.75em",
            },
            "thead th": {
              backgroundColor: theme("colors.neutral.100"),
              fontWeight: "600",
              color: theme("colors.neutral.800"),
              padding: "0.75rem 1rem",
            },
            "tbody td": {
              padding: "0.75rem 1rem",
              verticalAlign: "top",
            },
            "tbody tr:nth-child(even)": {
              backgroundColor: theme("colors.neutral.50"),
            },
            pre: {
              backgroundColor: theme("colors.neutral.900"),
              color: theme("colors.neutral.100"),
              borderRadius: "0.75rem",
              padding: "1.25rem 1.5rem",
              fontSize: "0.875rem",
              lineHeight: "1.65",
              overflowX: "auto",
            },
            code: {
              fontSize: "0.9em",
              fontWeight: "500",
            },
            "pre code": {
              backgroundColor: "transparent",
              color: "inherit",
              padding: 0,
              fontWeight: "400",
            },
            hr: {
              marginTop: "2.5em",
              marginBottom: "2.5em",
              borderColor: theme("colors.neutral.200"),
            },
          },
        },
      }),
    },
  },
  plugins: [typography],
};
